// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: follow_feed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFollowFeed = `-- name: CreateFollowFeed :one
INSERT INTO feed_follows(id, created_at, updated_at, user_id, feed_id)
VALUES($1,$2,$3,$4,$5)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateFollowFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateFollowFeed(ctx context.Context, arg CreateFollowFeedParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, createFollowFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const deleteFollowFeed = `-- name: DeleteFollowFeed :exec
DELETE  FROM  feed_follows WHERE id=$1 AND user_id=$2
`

type DeleteFollowFeedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFollowFeed(ctx context.Context, arg DeleteFollowFeedParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollowFeed, arg.ID, arg.UserID)
	return err
}

const getFollowFeed = `-- name: GetFollowFeed :many
SELECT id, created_at, updated_at, user_id, feed_id FROM  feed_follows WHERE user_id=$1
`

func (q *Queries) GetFollowFeed(ctx context.Context, userID uuid.UUID) ([]FeedFollow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowFeed, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollow
	for rows.Next() {
		var i FeedFollow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
